const countries = [
    {name: "Afghanistan",code: "AF",id: 1,phone: 93,symbol: "؋"},
    {name: "Åland Islands",code: "AX",id: 2,phone: 358,symbol: "€"},
    {name: "Albania",code: "AL",id: 3,phone: 355,symbol: "Lek"},
    {name: "Algeria",code: "DZ",id: 4,phone: 213,symbol: "دج"},
    {name: "American Samoa",code: "AS",id: 5,phone: 1684,symbol: "$"},
    {name: "Andorra",code: "AD",id: 6,phone: 376,symbol: "€"},
    {name: "Angola",code: "AO",id: 7,phone: 244,symbol: "Kz"},
    {name: "Anguilla",code: "AI",id: 8,phone: 1264,symbol: "$"},
    {name: "Antarctica",code: "AQ",id: 9,phone: 672,symbol: "$"},
    {name: "Antigua & Barbuda",code: "AG",id: 10,phone: 1268,symbol: "$"},
    {name: "Argentina",code: "AR",id: 11,phone: 54,symbol: "$"},
    {name: "Armenia",code: "AM",id: 12,phone: 374,symbol: "֏"},
    {name: "Aruba",code: "AW",id: 13,phone: 297,symbol: "ƒ"},
    {name: "Australia",code: "AU",id: 14,phone: 61,symbol: "$"},
    {name: "Austria",code: "AT",id: 15,phone: 43,symbol: "€"},
    {name: "Azerbaijan",code: "AZ",id: 16,phone: 994,symbol: "m"},
    {name: "Bahamas",code: "BS",id: 17,phone: 1242,symbol: "B$"},
    {name: "Bahrain",code: "BH",id: 18,phone: 973,symbol: ".د.ب"},
    {name: "Bangladesh",code: "BD",id: 19,phone: 880,symbol: "৳"},
    {name: "Barbados",code: "BB",id: 20,phone: 1246,symbol: "Bds$"},
    {name: "Belarus",code: "BY",id: 21,phone: 375,symbol: "Br"},
    {name: "Belgium",code: "BE",id: 22,phone: 32,symbol: "€"},
    {name: "Belize",code: "BZ",id: 23,phone: 501,symbol: "$"},
    {name: "Benin",code: "BJ",id: 24,phone: 229,symbol: "CFA"},
    {name: "Bermuda",code: "BM",id: 25,phone: 1441,symbol: "$"},
    {name: "Bhutan",code: "BT",id: 26,phone: 975,symbol: "Nu."},
    {name: "Bolivia",code: "BO",id: 27,phone: 591,symbol: "Bs."},
    {name: "Caribbean Netherlands",code: "BQ",id: 28,phone: 599,symbol: "$"},
    {name: "Bosnia & Herzegovina",code: "BA",id: 29,phone: 387,symbol: "KM"},
    {name: "Botswana",code: "BW",id: 30,phone: 267,symbol: "P"},
    {name: "Bouvet Island",code: "BV",id: 31,phone: 55,symbol: "kr"},
    {name: "Brazil",code: "BR",id: 32,phone: 55,symbol: "R$"},
    {name: "British Indian Ocean Territory",code: "IO",id: 33,phone: 246,symbol: "$"},
    {name: "Brunei",code: "BN",id: 34,phone: 673,symbol: "B$"},
    {name: "Bulgaria",code: "BG",id: 35,phone: 359,symbol: "Лв."},
    {name: "Burkina Faso",code: "BF",id: 36,phone: 226,symbol: "CFA"},
    {name: "Burundi",code: "BI",id: 37,phone: 257,symbol: "FBu"},
    {name: "Cambodia",code: "KH",id: 38,phone: 855,symbol: "KHR"},
    {name: "Cameroon",code: "CM",id: 39,phone: 237,symbol: "FCFA"},
    {name: "Canada",code: "CA",id: 40,phone: 1,symbol: "$"},
    {name: "Cape Verde",code: "CV",id: 41,phone: 238,symbol: "$"},
    {name: "Cayman Islands",code: "KY",id: 42,phone: 1345,symbol: "$"},
    {name: "Central African Republic",code: "CF",id: 43,phone: 236,symbol: "FCFA"},
    {name: "Chad",code: "TD",id: 44,phone: 235,symbol: "FCFA"},
    {name: "Chile",code: "CL",id: 45,phone: 56,symbol: "$"},
    {name: "China",code: "CN",id: 46,phone: 86,symbol: "¥"},
    {name: "Christmas Island",code: "CX",id: 47,phone: 61,symbol: "$"},
    {name: "Cocos (Keeling) Islands",code: "CC",id: 48,phone: 672,symbol: "$"},
    {name: "Colombia",code: "CO",id: 49,phone: 57,symbol: "$"},
    {name: "Comoros",code: "KM",id: 50,phone: 269,symbol: "CF"},
    {name: "Congo - Brazzaville",code: "CG",id: 51,phone: 242,symbol: "FC"},
    {name: "Congo - Kinshasa",code: "CD",id: 52,phone: 242,symbol: "FC"},
    {name: "Cook Islands",code: "CK",id: 53,phone: 682,symbol: "$"},
    {name: "Costa Rica",code: "CR",id: 54,phone: 506,symbol: "₡"},
    {name: "Côte d’Ivoire",code: "CI",id: 55,phone: 225,symbol: "CFA"},
    {name: "Croatia",code: "HR",id: 56,phone: 385,symbol: "kn"},
    {name: "Cuba",code: "CU",id: 57,phone: 53,symbol: "$"},
    {name: "Curaçao",code: "CW",id: 58,phone: 599,symbol: "ƒ"},
    {name: "Cyprus",code: "CY",id: 59,phone: 357,symbol: "€"},
    {name: "Czechia",code: "CZ",id: 60,phone: 420,symbol: "Kč"},
    {name: "Denmark",code: "DK",id: 61,phone: 45,symbol: "Kr."},
    {name: "Djibouti",code: "DJ",id: 62,phone: 253,symbol: "Fdj"},
    {name: "Dominica",code: "DM",id: 63,phone: 1767,symbol: "$"},
    {name: "Dominican Republic",code: "DO",id: 64,phone: 1809,symbol: "$"},
    {name: "Ecuador",code: "EC",id: 65,phone: 593,symbol: "$"},
    {name: "Egypt",code: "EG",id: 66,phone: 20,symbol: "ج.م"},
    {name: "El Salvador",code: "SV",id: 67,phone: 503,symbol: "$"},
    {name: "Equatorial Guinea",code: "GQ",id: 68,phone: 240,symbol: "FCFA"},
    {name: "Eritrea",code: "ER",id: 69,phone: 291,symbol: "Nfk"},
    {name: "Estonia",code: "EE",id: 70,phone: 372,symbol: "€"},
    {name: "Ethiopia",code: "ET",id: 71,phone: 251,symbol: "Nkf"},
    {name: "Falkland Islands (Islas Malvinas)",code: "FK",id: 72,phone: 500,symbol: "£"},
    {name: "Faroe Islands",code: "FO",id: 73,phone: 298,symbol: "Kr."},
    {name: "Fiji",code: "FJ",id: 74,phone: 679,symbol: "FJ$"},
    {name: "Finland",code: "FI",id: 75,phone: 358,symbol: "€"},
    {name: "France",code: "FR",id: 76,phone: 33,symbol: "€"},
    {name: "French Guiana",code: "GF",id: 77,phone: 594,symbol: "€"},
    {name: "French Polynesia",code: "PF",id: 78,phone: 689,symbol: "₣"},
    {name: "French Southern Territories",code: "TF",id: 79,phone: 262,symbol: "€"},
    {name: "Gabon",code: "GA",id: 80,phone: 241,symbol: "FCFA"},
    {name: "Gambia",code: "GM",id: 81,phone: 220,symbol: "D"},
    {name: "Georgia",code: "GE",id: 82,phone: 995,symbol: "ლ"},
    {name: "Germany",code: "DE",id: 83,phone: 49,symbol: "€"},
    {name: "Ghana",code: "GH",id: 84,phone: 233,symbol: "GH₵"},
    {name: "Gibraltar",code: "GI",id: 85,phone: 350,symbol: "£"},
    {name: "Greece",code: "GR",id: 86,phone: 30,symbol: "€"},
    {name: "Greenland",code: "GL",id: 87,phone: 299,symbol: "Kr."},
    {name: "Grenada",code: "GD",id: 88,phone: 1473,symbol: "$"},
    {name: "Guadeloupe",code: "GP",id: 89,phone: 590,symbol: "€"},
    {name: "Guam",code: "GU",id: 90,phone: 1671,symbol: "$"},
    {name: "Guatemala",code: "GT",id: 91,phone: 502,symbol: "Q"},
    {name: "Guernsey",code: "GG",id: 92,phone: 44,symbol: "£"},
    {name: "Guinea",code: "GN",id: 93,phone: 224,symbol: "FG"},
    {name: "Guinea-Bissau",code: "GW",id: 94,phone: 245,symbol: "CFA"},
    {name: "Guyana",code: "GY",id: 95,phone: 592,symbol: "$"},
    {name: "Haiti",code: "HT",id: 96,phone: 509,symbol: "G"},
    {name: "Heard & McDonald Islands",code: "HM",id: 97,phone: 0,symbol: "$"},
    {name: "Vatican City",code: "VA",id: 98,phone: 39,symbol: "€"},
    {name: "Honduras",code: "HN",id: 99,phone: 504,symbol: "L"},
    {name: "Hong Kong",code: "HK",id: 100,phone: 852,symbol: "$"},
    {name: "Hungary",code: "HU",id: 101,phone: 36,symbol: "Ft"},
    {name: "Iceland",code: "IS",id: 102,phone: 354,symbol: "kr"},
    {name: "India",code: "IN",id: 103,phone: 91,symbol: "₹"},
    {name: "Indonesia",code: "ID",id: 104,phone: 62,symbol: "Rp"},
    {name: "Iran",code: "IR",id: 105,phone: 98,symbol: "﷼"},
    {name: "Iraq",code: "IQ",id: 106,phone: 964,symbol: "د.ع"},
    {name: "Ireland",code: "IE",id: 107,phone: 353,symbol: "€"},
    {name: "Isle of Man",code: "IM",id: 108,phone: 44,symbol: "£"},
    {name: "Israel",code: "IL",id: 109,phone: 972,symbol: "₪"},
    {name: "Italy",code: "IT",id: 110,phone: 39,symbol: "€"},
    {name: "Jamaica",code: "JM",id: 111,phone: 1876,symbol: "J$"},
    {name: "Japan",code: "JP",id: 112,phone: 81,symbol: "¥"},
    {name: "Jersey",code: "JE",id: 113,phone: 44,symbol: "£"},
    {name: "Jordan",code: "JO",id: 114,phone: 962,symbol: "ا.د"},
    {name: "Kazakhstan",code: "KZ",id: 115,phone: 7,symbol: "лв"},
    {name: "Kenya",code: "KE",id: 116,phone: 254,symbol: "KSh"},
    {name: "Kiribati",code: "KI",id: 117,phone: 686,symbol: "$"},
    {name: "North Korea",code: "KP",id: 118,phone: 850,symbol: "₩"},
    {name: "South Korea",code: "KR",id: 119,phone: 82,symbol: "₩"},
    {name: "Kosovo",code: "XK",id: 120,phone: 381,symbol: "€"},
    {name: "Kuwait",code: "KW",id: 121,phone: 965,symbol: "ك.د"},
    {name: "Kyrgyzstan",code: "KG",id: 122,phone: 996,symbol: "лв"},
    {name: "Laos",code: "LA",id: 123,phone: 856,symbol: "₭"},
    {name: "Latvia",code: "LV",id: 124,phone: 371,symbol: "€"},
    {name: "Lebanon",code: "LB",id: 125,phone: 961,symbol: "£"},
    {name: "Lesotho",code: "LS",id: 126,phone: 266,symbol: "L"},
    {name: "Liberia",code: "LR",id: 127,phone: 231,symbol: "$"},
    {name: "Libya",code: "LY",id: 128,phone: 218,symbol: "د.ل"},
    {name: "Liechtenstein",code: "LI",id: 129,phone: 423,symbol: "CHf"},
    {name: "Lithuania",code: "LT",id: 130,phone: 370,symbol: "€"},
    {name: "Luxembourg",code: "LU",id: 131,phone: 352,symbol: "€"},
    {name: "Macao",code: "MO",id: 132,phone: 853,symbol: "$"},
    {name: "North Macedonia",code: "MK",id: 133,phone: 389,symbol: "ден"},
    {name: "Madagascar",code: "MG",id: 134,phone: 261,symbol: "Ar"},
    {name: "Malawi",code: "MW",id: 135,phone: 265,symbol: "MK"},
    {name: "Malaysia",code: "MY",id: 136,phone: 60,symbol: "RM"},
    {name: "Maldives",code: "MV",id: 137,phone: 960,symbol: "Rf"},
    {name: "Mali",code: "ML",id: 138,phone: 223,symbol: "CFA"},
    {name: "Malta",code: "MT",id: 139,phone: 356,symbol: "€"},
    {name: "Marshall Islands",code: "MH",id: 140,phone: 692,symbol: "$"},
    {name: "Martinique",code: "MQ",id: 141,phone: 596,symbol: "€"},
    {name: "Mauritania",code: "MR",id: 142,phone: 222,symbol: "MRU"},
    {name: "Mauritius",code: "MU",id: 143,phone: 230,symbol: "₨"},
    {name: "Mayotte",code: "YT",id: 144,phone: 262,symbol: "€"},
    {name: "Mexico",code: "MX",id: 145,phone: 52,symbol: "$"},
    {name: "Micronesia",code: "FM",id: 146,phone: 691,symbol: "$"},
    {name: "Moldova",code: "MD",id: 147,phone: 373,symbol: "L"},
    {name: "Monaco",code: "MC",id: 148,phone: 377,symbol: "€"},
    {name: "Mongolia",code: "MN",id: 149,phone: 976,symbol: "₮"},
    {name: "Montenegro",code: "ME",id: 150,phone: 382,symbol: "€"},
    {name: "Montserrat",code: "MS",id: 151,phone: 1664,symbol: "$"},
    {name: "Morocco",code: "MA",id: 152,phone: 212,symbol: "DH"},
    {name: "Mozambique",code: "MZ",id: 153,phone: 258,symbol: "MT"},
    {name: "Myanmar (Burma)",code: "MM",id: 154,phone: 95,symbol: "K"},
    {name: "Namibia",code: "NA",id: 155,phone: 264,symbol: "$"},
    {name: "Nauru",code: "NR",id: 156,phone: 674,symbol: "$"},
    {name: "Nepal",code: "NP",id: 157,phone: 977,symbol: "₨"},
    {name: "Netherlands",code: "NL",id: 158,phone: 31,symbol: "€"},
    {name: "Curaçao",code: "AN",id: 159,phone: 599,symbol: "NAf"},
    {name: "New Caledonia",code: "NC",id: 160,phone: 687,symbol: "₣"},
    {name: "New Zealand",code: "NZ",id: 161,phone: 64,symbol: "$"},
    {name: "Nicaragua",code: "NI",id: 162,phone: 505,symbol: "C$"},
    {name: "Niger",code: "NE",id: 163,phone: 227,symbol: "CFA"},
    {name: "Nigeria",code: "NG",id: 164,phone: 234,symbol: "₦"},
    {name: "Niue",code: "NU",id: 165,phone: 683,symbol: "$"},
    {name: "Norfolk Island",code: "NF",id: 166,phone: 672,symbol: "$"},
    {name: "Northern Mariana Islands",code: "MP",id: 167,phone: 1670,symbol: "$"},
    {name: "Norway",code: "NO",id: 168,phone: 47,symbol: "kr"},
    {name: "Oman",code: "OM",id: 169,phone: 968,symbol: ".ع.ر"},
    {name: "Pakistan",code: "PK",id: 170,phone: 92,symbol: "₨"},
    {name: "Palau",code: "PW",id: 171,phone: 680,symbol: "$"},
    {name: "Palestine",code: "PS",id: 172,phone: 970,symbol: "₪"},
    {name: "Panama",code: "PA",id: 173,phone: 507,symbol: "B/."},
    {name: "Papua New Guinea",code: "PG",id: 174,phone: 675,symbol: "K"},
    {name: "Paraguay",code: "PY",id: 175,phone: 595,symbol: "₲"},
    {name: "Peru",code: "PE",id: 176,phone: 51,symbol: "S/."},
    {name: "Philippines",code: "PH",id: 177,phone: 63,symbol: "₱"},
    {name: "Pitcairn Islands",code: "PN",id: 178,phone: 64,symbol: "$"},
    {name: "Poland",code: "PL",id: 179,phone: 48,symbol: "zł"},
    {name: "Portugal",code: "PT",id: 180,phone: 351,symbol: "€"},
    {name: "Puerto Rico",code: "PR",id: 181,phone: 1787,symbol: "$"},
    {name: "Qatar",code: "QA",id: 182,phone: 974,symbol: "ق.ر"},
    {name: "Réunion",code: "RE",id: 183,phone: 262,symbol: "€"},
    {name: "Romania",code: "RO",id: 184,phone: 40,symbol: "lei"},
    {name: "Russia",code: "RU",id: 185,phone: 70,symbol: "₽"},
    {name: "Rwanda",code: "RW",id: 186,phone: 250,symbol: "FRw"},
    {name: "St. Barthélemy",code: "BL",id: 187,phone: 590,symbol: "€"},
    {name: "St. Helena",code: "SH",id: 188,phone: 290,symbol: "£"},
    {name: "St. Kitts & Nevis",code: "KN",id: 189,phone: 1869,symbol: "$"},
    {name: "St. Lucia",code: "LC",id: 190,phone: 1758,symbol: "$"},
    {name: "St. Martin",code: "MF",id: 191,phone: 590,symbol: "€"},
    {name: "St. Pierre & Miquelon",code: "PM",id: 192,phone: 508,symbol: "€"},
    {name: "St. Vincent & Grenadines",code: "VC",id: 193,phone: 1784,symbol: "$"},
    {name: "Samoa",code: "WS",id: 194,phone: 684,symbol: "SAT"},
    {name: "San Marino",code: "SM",id: 195,phone: 378,symbol: "€"},
    {name: "São Tomé & Príncipe",code: "ST",id: 196,phone: 239,symbol: "Db"},
    {name: "Saudi Arabia",code: "SA",id: 197,phone: 966,symbol: "﷼"},
    {name: "Senegal",code: "SN",id: 198,phone: 221,symbol: "CFA"},
    {name: "Serbia",code: "RS",id: 199,phone: 381,symbol: "din"},
    {name: "Serbia",code: "CS",id: 200,phone: 381,symbol: "din"},
    {name: "Seychelles",code: "SC",id: 201,phone: 248,symbol: "SRe"},
    {name: "Sierra Leone",code: "SL",id: 202,phone: 232,symbol: "Le"},
    {name: "Singapore",code: "SG",id: 203,phone: 65,symbol: "$"},
    {name: "Sint Maarten",code: "SX",id: 204,phone: 1,symbol: "ƒ"},
    {name: "Slovakia",code: "SK",id: 205,phone: 421,symbol: "€"},
    {name: "Slovenia",code: "SI",id: 206,phone: 386,symbol: "€"},
    {name: "Solomon Islands",code: "SB",id: 207,phone: 677,symbol: "Si$"},
    {name: "Somalia",code: "SO",id: 208,phone: 252,symbol: "Sh.so."},
    {name: "South Africa",code: "ZA",id: 209,phone: 27,symbol: "R"},
    {name: "South Georgia & South Sandwich Islands",code: "GS",id: 210,phone: 500,symbol: "£"},
    {name: "South Sudan",code: "SS",id: 211,phone: 211,symbol: "£"},
    {name: "Spain",code: "ES",id: 212,phone: 34,symbol: "€"},
    {name: "Sri Lanka",code: "LK",id: 213,phone: 94,symbol: "Rs"},
    {name: "Sudan",code: "SD",id: 214,phone: 249,symbol: ".س.ج"},
    {name: "Suriname",code: "SR",id: 215,phone: 597,symbol: "$"},
    {name: "Svalbard & Jan Mayen",code: "SJ",id: 216,phone: 47,symbol: "kr"},
    {name: "Eswatini",code: "SZ",id: 217,phone: 268,symbol: "E"},
    {name: "Sweden",code: "SE",id: 218,phone: 46,symbol: "kr"},
    {name: "Switzerland",code: "CH",id: 219,phone: 41,symbol: "CHf"},
    {name: "Syria",code: "SY",id: 220,phone: 963,symbol: "LS"},
    {name: "Taiwan",code: "TW",id: 221,phone: 886,symbol: "$"},
    {name: "Tajikistan",code: "TJ",id: 222,phone: 992,symbol: "SM"},
    {name: "Tanzania",code: "TZ",id: 223,phone: 255,symbol: "TSh"},
    {name: "Thailand",code: "TH",id: 224,phone: 66,symbol: "฿"},
    {name: "Timor-Leste",code: "TL",id: 225,phone: 670,symbol: "$"},
    {name: "Togo",code: "TG",id: 226,phone: 228,symbol: "CFA"},
    {name: "Tokelau",code: "TK",id: 227,phone: 690,symbol: "$"},
    {name: "Tonga",code: "TO",id: 228,phone: 676,symbol: "$"},
    {name: "Trinidad & Tobago",code: "TT",id: 229,phone: 1868,symbol: "$"},
    {name: "Tunisia",code: "TN",id: 230,phone: 216,symbol: "ت.د"},
    {name: "Turkey",code: "TR",id: 231,phone: 90,symbol: "₺"},
    {name: "Turkmenistan",code: "TM",id: 232,phone: 7370,symbol: "T"},
    {name: "Turks & Caicos Islands",code: "TC",id: 233,phone: 1649,symbol: "$"},
    {name: "Tuvalu",code: "TV",id: 234,phone: 688,symbol: "$"},
    {name: "Uganda",code: "UG",id: 235,phone: 256,symbol: "USh"},
    {name: "Ukraine",code: "UA",id: 236,phone: 380,symbol: "₴"},
    {name: "United Arab Emirates",code: "AE",id: 237,phone: 971,symbol: "إ.د"},
    {name: "United Kingdom",code: "GB",id: 238,phone: 44,symbol: "£"},
    {name: "United States",code: "US",id: 239,phone: 1,symbol: "$"},
    {name: "U.S. Outlying Islands",code: "UM",id: 240,phone: 1,symbol: "$"},
    {name: "Uruguay",code: "UY",id: 241,phone: 598,symbol: "$"},
    {name: "Uzbekistan",code: "UZ",id: 242,phone: 998,symbol: "лв"},
    {name: "Vanuatu",code: "VU",id: 243,phone: 678,symbol: "VT"},
    {name: "Venezuela",code: "VE",id: 244,phone: 58,symbol: "Bs"},
    {name: "Vietnam",code: "VN",id: 245,phone: 84,symbol: "₫"},
    {name: "British Virgin Islands",code: "VG",id: 246,phone: 1284,symbol: "$"},
    {name: "U.S. Virgin Islands",code: "VI",id: 247,phone: 1340,symbol: "$"},
    {name: "Wallis & Futuna",code: "WF",id: 248,phone: 681,symbol: "₣"},
    {name: "Western Sahara",code: "EH",id: 249,phone: 212,symbol: "MAD"},
    {name: "Yemen",code: "YE",id: 250,phone: 967,symbol: "﷼"},
    {name: "Zambia",code: "ZM",id: 251,phone: 260,symbol: "ZK"},
    {name: "Zimbabwe",code: "ZW",id: 252,phone: 263,symbol: "$"}
];
export default countries;